const gptProductObject = {
    "categories":[
        "Sportswear",
        "Outerwear",
        "Footwear"
    ],
    "products":[
        {
            "title":"Tailored Sports Jacket",
            "description":"",
            "tags":[
                "Sportswear"
            ],
            "price":"125.00",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "XS",
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Black",
                        "Grey",
                        "Blue"
                    ]
                }
            ],
            "productType":"Jacket",
            "requiresShipping":true,
            "weight":500,
            "weightUnit":"g"
        },
        {
            "title":"Warm Fleece Sweatshirt",
            "description":"",
            "tags":[
                "Sportswear"
            ],
            "price":"59.95",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "XS",
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Navy",
                        "White",
                        "Charcoal Grey"
                    ]
                }
            ],
            "productType":"Sweatshirt",
            "requiresShipping":true,
            "weight":400,
            "weightUnit":"g"
        },
        {
            "title":"Fashionable Leather Boots",
            "description":"",
            "tags":[
                "Footwear"
            ],
            "price":"179.99",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "5",
                        "6",
                        "7",
                        "8",
                        "9"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Brown",
                        "Tan",
                        "Black"
                    ]
                }
            ],
            "productType":"Boots",
            "requiresShipping":true,
            "weight":800,
            "weightUnit":"g"
        },
        {
            "title":"Chunky Wool Cardigan",
            "description":"",
            "tags":[
                "Outerwear"
            ],
            "price":"69.99",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Mustard Yellow",
                        "Crimson Red",
                        "Camel Brown"
                    ]
                }
            ],
            "productType":"Cardigan",
            "requiresShipping":true,
            "weight":300,
            "weightUnit":"g"
        },
        {
            "title":"Stylish Running Shoes",
            "description":"",
            "tags":[
                "Footwear"
            ],
            "price":"99.95",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "36",
                        "37",
                        "38",
                        "39",
                        "40"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Orange",
                        "Royal Blue",
                        "Neon Green"
                    ]
                }
            ],
            "productType":"Shoes",
            "requiresShipping":true,
            "weight":650,
            "weightUnit":"g"
        },
        {
            "title":"Striped Track Suit Pants",
            "description":"",
            "tags":[
                "Sportswear"
            ],
            "price":"34.99",
            "compareAtPrice":"49.99",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "XS",
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Red Stripe",
                        "Blue Stripe",
                        "Green Stripe"
                    ]
                }
            ],
            "productType":"Pants",
            "requiresShipping":true,
            "weight":350,
            "weightUnit":"g"
        },
        {
            "title":"Trendy Denim Jean Jacket",
            "description":"",
            "tags":[
                "Outerwear"
            ],
            "price":"79.95",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "XS",
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Light Wash",
                        "Medium Wash",
                        "Dark Wash"
                    ]
                }
            ],
            "productType":"Jacket",
            "requiresShipping":true,
            "weight":450,
            "weightUnit":"g"
        },
        {
            "title":"Cozy Quilted Winter Coat",
            "description":"",
            "tags":[
                "Outerwear"
            ],
            "price":"139.99",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Off-White",
                        "Midnight Navy",
                        "Slate Grey"
                    ]
                }
            ],
            "productType":"Coat",
            "requiresShipping":true,
            "weight":750,
            "weightUnit":"g"
        },
        {
            "title":"Comfortable Hiking Sandals",
            "description":"",
            "tags":[
                "Footwear"
            ],
            "price":"45.00",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "4",
                        "5",
                        "6",
                        "7",
                        "8"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Beige",
                        "Khaki",
                        "Olive Drab"
                    ]
                }
            ],
            "productType":"Sandals",
            "requiresShipping":true,
            "weight":550,
            "weightUnit":"g"
        },
        {
            "title":"Vibrant Zip Up Hoodie",
            "description":"",
            "tags":[
                "Sportswear"
            ],
            "price":"54.99",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Yellow",
                        "Turquoise",
                        "Pink"
                    ]
                }
            ],
            "productType":"Hoodie",
            "requiresShipping":true,
            "weight":500,
            "weightUnit":"g"
        },
        {
            "title":"Fancy Strapped Heels",
            "description":"",
            "tags":[
                "Footwear"
            ],
            "price":"109.99",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "5",
                        "6",
                        "7",
                        "8",
                        "9"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Silver",
                        "Gold",
                        "Rose Gold"
                    ]
                }
            ],
            "productType":"Heels",
            "requiresShipping":true,
            "weight":700,
            "weightUnit":"g"
        },
        {
            "title":"All Day Cargo Shorts",
            "description":"",
            "tags":[
                "Sportswear"
            ],
            "price":"29.99",
            "compareAtPrice":"39.99",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "30",
                        "32",
                        "34",
                        "36",
                        "38"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Khaki",
                        "Stone",
                        "Olive"
                    ]
                }
            ],
            "productType":"Shorts",
            "requiresShipping":true,
            "weight":450,
            "weightUnit":"g"
        },
        {
            "title":"Plush Sherpa House Slippers",
            "description":"",
            "tags":[
                "Footwear"
            ],
            "price":"19.95",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "Small",
                        "Medium",
                        "Large"
                    ]
                }
            ],
            "productType":"Slippers",
            "requiresShipping":true,
            "weight":200,
            "weightUnit":"g"
        },
        {
            "title":"Heavy Duty Rain Trenchcoat",
            "description":"",
            "tags":[
                "Outerwear"
            ],
            "price":"89.99",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Sky Blue",
                        "Graphite Grey",
                        "Hunter Green"
                    ]
                }
            ],
            "productType":"Coat",
            "requiresShipping":true,
            "weight":900,
            "weightUnit":"g"
        },
        {
            "title":"Glamorous Off-the-Shoulder Top",
            "description":"",
            "tags":[
                "Sportswear"
            ],
            "price":"54.99",
            "compareAtPrice":"",
            "options":[
                {
                    "name":"size",
                    "values":[
                        "XS",
                        "S",
                        "M",
                        "L",
                        "XL"
                    ]
                },
                {
                    "name":"colour",
                    "values":[
                        "Dusty Rose",
                        "Metallic Silver",
                        "Bright Coral"
                    ]
                }
            ],
            "productType":"Top",
            "requiresShipping":true,
            "weight":250,
            "weightUnit":"g"
        }
    ]
}

export default gptProductObject;